### ISSUE TITLE
🛑 Beans Hosting Client and Payment Panel is down

### ISSUE THREAD

**Issue by MDCYT** [BeansHosting-net/status.beanshosting.net#6]
In [`fe95190`](https://github.com/BeansHosting-net/status.beanshosting.net/commit/fe95190e3d67e83f9350bc2c7d52d186c0294717
), Beans Hosting Client and Payment Panel ($NODE_1_USA_IP) was **down**:
- HTTP code: 0
- Response time: 0 ms

**Comment by BeansHosting** [comment]
We are under maintenance
